#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Contracts\Console\Kernel as ConsoleKernel;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';

// ✅ Correct binding: interface -> implementation
$app->singleton(
    // ConsoleKernel::class,
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

// Handle the Artisan command
$status = $app->handleCommand(new ArgvInput);
exit($status);
